### ISSUE TITLE
IC19 ROn

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#223]
Probably not an issue, but just to check, why is RON so high for IC19? Shouldn't it be close to 100k for 6V?

**Comment by gkasprow** [comment]
could be lower. It sets operating frequency.
I copied it from some working project
The DS says
ON-timeresistor.An external resistor between this pin and the VIN pin sets the ON-time of the application.Typical values range from 25 kΩ to 124 kΩ
![obraz](https://user-images.githubusercontent.com/4325054/59464267-480a9580-8e28-11e9-8d00-76ef6b5e808b.png)
We should lower it to 100k since it is recommended value for 5V output
