### ISSUE TITLE
errata

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#25]
@gkasprow please can you post a list of all fixes you've applied during your bug testing, please?

**Comment by gkasprow** [comment]
Main board:
- added current limiting resistor 0.18Ohm instead of embedded 0.025Ohm between pin 7 and pad 8 of U1(A,B,C..), disconnect pin 8.
- remove resistors in Vbias LDO: R87(A,B,C...) = 27k

RFPA_OUT
- removed 2 feedback resistors in OA, R32, R31
- shorted threshold regulation divider, R24 = 0R
- added 56R in parallel to C4 to change Vbias range from 1.7....3.2 to 1...1.8
- removed EEPROMIC (U8)

RFPA_PREAMP
- shorted threshold regulation divider, R29 = 0R
- removed feedback resistor in OA, R31

**Comment by hartytp** [comment]
:+1: thanks!

**Comment by wizath** [comment]
Main board:
- Neg voltage:
-- R87 - 22k
-- R86 - 10k
- 5V LDO
-- R10 - 12k
-- R13 - 3k9
- 30V LDO
-- R8 - 16k
-- R9 - 1k6
