### ISSUE TITLE
scpi interface crashes

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#340]
...

**Comment by gkasprow** [comment]
The plan is to buy a trace interface which dumps real-time data via SS USB.
Currently, the situation is very tough to debug since it crashes the entire RTOS.
We will isolate the problematic issue and recreate it on devkit with just Ethernet and SCPI thread. 
With a real-time record of all functions calls and stack, we should be able to get into the real cause.

**Comment by hartytp** [comment]
Uuurgh...

Glad you have a plan for this. What a pain though

**Comment by hartytp** [comment]
duplicate of #327
