### ISSUE TITLE
Add TVSs

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#344]
See https://github.com/sinara-hw/Booster/issues/329

**Comment by hartytp** [comment]
@gkasprow can you draw out what the new circuit with TVS should look like so we have a record of what patches are being implemented?

**Comment by gkasprow** [comment]
The addition of the TVS is very simple. One does not have to remove the board from the enclosure nor disconnect the RF cable.
The input TVS consists of two diodes in one SOT-23 package. Leads 1 and 2 must be shorted to GND. Lead 3 goes to the RF track.
Alternatively lead 3 goes to GND and leads 1,2 go to the RF track.
One way - simpler but less elegant
![2019-12-19 16 13 11](https://user-images.githubusercontent.com/4325054/71206322-93ed3a00-22a4-11ea-9335-420f83c156b0.jpg)
The other way - more complex because one must scratch the solder resist
![2019-12-19 14 09 19](https://user-images.githubusercontent.com/4325054/71206398-bb440700-22a4-11ea-819b-b1134bce34db.jpg)

**Comment by gkasprow** [comment]
The first stage output TVS can be added quickly.
It is 6V8 bidir TVS [AQ4021-01FTG-C ](https://pl.mouser.com/datasheet/2/240/littelfuse_tvs_diode_array_aqxxc-01ftg_datasheet.p-1531773.pdf) Bidir ones have lower capacitance because there are 2 diodes connected in series. In our case, we don't care if it is uni-dir or bi-dir.

![2019-12-19 16 13 34](https://user-images.githubusercontent.com/4325054/71206466-e0d11080-22a4-11ea-914c-ad3ef1d37f97.jpg)

**Comment by gkasprow** [comment]
The MOSFET needs the TVS at the gate as well. I used AQ4020-01FTG which is easy to solder and has 2.5pF capacitance and 3.5V breakdown voltage. What is important, it must be uni-dir TVS because we don't want a positive voltage on the gate because just 3V can kill the transistor. One could also use here and at the output of the first stage the same 6V uni-dir TVS. The cathode goes to GND!

One can add it in less elegant way
![2019-12-19 16 13 51](https://user-images.githubusercontent.com/4325054/71206997-2c37ee80-22a6-11ea-884b-8eb76098a35f.jpg)

or in more elegant way, that needs scratching of the solder resist.
![2019-12-19 14 11 38](https://user-images.githubusercontent.com/4325054/71207049-41ad1880-22a6-11ea-98ad-460ac363d926.jpg)

**Comment by gkasprow** [comment]
The TVS protecting the output must protect it against too high voltages that can occur during operation without the load. The transistor sustains up to 100V of the drain voltage so we need some clipping between 45 and 90V. I could not find easy to obtain low C TVS so I used two standard 0.5W BZT55-series 33V Zener diodes (i.e. BZT55C33) in series with low capacitance TVS diode. Not very elegant but works.

![2019-12-19 14 12 02](https://user-images.githubusercontent.com/4325054/71207342-fb0bee00-22a6-11ea-8f33-e8373f343a1c.jpg)
![2019-12-19 16 14 17](https://user-images.githubusercontent.com/4325054/71207357-ffd0a200-22a6-11ea-8c09-1733e3749b4d.jpg)

DO NOT CONNECT the pad 2

**Comment by hartytp** [comment]
Nice! Hopefully that'll be the end of the odd behaviour in Booster!

**Comment by gkasprow** [comment]
With these components, it's very hard to exceed ratings of the amplifier.
Another aspect is the soldering of the power FET thermal pad which was an issue in 3 cases.

**Comment by hartytp** [comment]
> Another aspect is the soldering of the power FET thermal pad which was an issue in 3 cases.

What's the plan for that? Better QC?

**Comment by gkasprow** [comment]
We can activate the FET thermal pad surface prior to soldering.

**Comment by gkasprow** [comment]
Schematic changes:
Input TVS
![obraz](https://user-images.githubusercontent.com/4325054/71216199-2a782600-22ba-11ea-922e-547b81852811.png)
1-st stage TVS
![obraz](https://user-images.githubusercontent.com/4325054/71216212-35cb5180-22ba-11ea-8c8d-f2c924fe776a.png)
Gate TVS
![obraz](https://user-images.githubusercontent.com/4325054/71216228-45e33100-22ba-11ea-9584-051ac0dc2f6b.png)
Output TVS
![obraz](https://user-images.githubusercontent.com/4325054/71216357-96f32500-22ba-11ea-83a1-8dcf8dbd0a80.png)

**Comment by hartytp** [comment]
Shouldn't the input TVS be placed after the switch to protect the first stage pre-amp from the glitches generated by the internal switch?

Or are you trying to protect the switch itself?

**Comment by hartytp** [comment]
Why not use a bidir TVS on the FET (don't you also want this to protect the second stage output)?

Do you need a TVS on the second stage input (after the AC coupling cap)?

**Comment by gkasprow** [comment]
The switch glitches are smaller than 0.7V so TVS won't remove them.
FET has a safe operating range from +3.-10. TVS has a diode in parallel. So it protects the second stage output as well, clipping transients to 0.7V

**Comment by hartytp** [comment]
> The switch glitches are smaller than 0.7V so TVS won't remove them.

Okay, I remember now -- the point is that the input glitch is small but it saturates the amp quickly and produces a large glitch at the output.

**Comment by hartytp** [comment]
> So it protects the second stage output as well, clipping transients to 0.7V

Okay, I'd need to think about this. Aren't there DC block capacitors there that can charge up so a TVS on the gate won't necessarily protect the output of the 2nd stage.

**Comment by gkasprow** [comment]
The output of the second stage is loaded with 680p and then TVS diode to GND. Moreover, it has a feedback loop that reduces the output signal rise time. So the output spike has to charge both C50 and C44 using L5 energy. The first stage has only 39pF of C40.

**Comment by gkasprow** [comment]
added in v1.5
