### ISSUE TITLE
booster self testing capability

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#394]
Since Booster is a pretty popular device produced in large batches, we need to improve its testability.
For example, we had issues with the input voltage being too high because somebody forgot to adjust the SMPS output voltage to 31V, and the default 36V was used, which led to LDO overheating.
The proposed changes do not affect existing firmware and will be used only in the production environment:
- add a voltage divider that measures input voltages from SMPS modules and routes them to CPU ADC
- add NTC thermistors or LM75 or LM35 under the channel LDOs and route them to unused inputs of IC9x or CPU ADC or I2C bus
- add a voltage divider that measures P28V at each channel and route it to unused inputs of IC9x or CPU ADC

**Comment by jordens** [comment]
The restriction to PTS is a bad idea. If there is self-testing capability in the hardware it should always be exposed and used everywhere, not just while producing. Otherwise the corresponding software will see little to no maintenance, will diverge and the benefit of being able to self-test and monitor in use is lost. There is no point in restricting it.

**Comment by gkasprow** [comment]
I'm not going to restrict it. We need these capabilities for production testing. They will be transparent to existing firmware. Sure, it's good from the manufacturer's perspective to diagnose the HW remotely.

**Comment by gkasprow** [comment]
I added a simple circuit that prevents from starting Booster when the 30V rail is too high.
![obraz](https://github.com/user-attachments/assets/70edc070-c546-4cbc-9af3-1af3960d2072)
